version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 363838752048.dkr.ecr.us-west-2.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t berlofa-apache-php .
      - docker tag berlofa-apache-php:latest 363838752048.dkr.ecr.us-west-2.amazonaws.com/appmaicon:latest
      - docker tag berlofa-apache-php:latest 363838752048.dkr.ecr.us-west-2.amazonaws.com/appmaicon:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 363838752048.dkr.ecr.us-west-2.amazonaws.com/appmaicon:latest
      - docker push 363838752048.dkr.ecr.us-west-2.amazonaws.com/appmaicon:$IMAGE_TAG

artifacts:
  files: '**/*'
